from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class PerAssertionResult:
    """Result of a single test assertion evaluation."""

    assertion: str
    passed: bool
    error: str | None = None


@dataclass
class Feedback:
    """Structured failure diagnostic F(i,j) (§3.3).

    Generated by the Surrogate Verifier when R̃ < 1.
    Includes per-assertion results, root-cause analysis, and actionable
    revision suggestions for the Skill Generator.

    This is appended to the generator's conversation context C to drive
    skill refinement (Eq.7).
    """

    overall_pass: bool
    surrogate_reward: float
    assertion_results: list[PerAssertionResult] = field(default_factory=list)
    root_cause_analysis: str = ""
    revision_suggestions: list[str] = field(default_factory=list)

    @property
    def passed_count(self) -> int:
        return sum(1 for r in self.assertion_results if r.passed)

    @property
    def failed_count(self) -> int:
        return sum(1 for r in self.assertion_results if not r.passed)

    @property
    def total_count(self) -> int:
        return len(self.assertion_results)

    def to_context_str(self) -> str:
        """Serialize diagnostic as a string to append to generator context C.

        The format is designed to be dense and actionable:
        - Pass/fail summary
        - Per-test results with error details
        - Root-cause analysis
        - Revision suggestions
        """
        lines: list[str] = [
            "=== VERIFICATION FAILURE REPORT ===",
            f"Surrogate reward R̃ = {self.surrogate_reward:.2f} ({self.passed_count}/{self.total_count} passed)",
            "",
            "--- Failed assertions ---",
        ]

        for result in self.assertion_results:
            if not result.passed:
                assertion_preview = result.assertion[:200].replace("\n", " ").strip()
                lines.append(f"  FAIL: {assertion_preview}")
                if result.error:
                    lines.append(f"    Error: {result.error}")

        if self.root_cause_analysis:
            lines.append("")
            lines.append("--- Root-cause analysis ---")
            lines.append(self.root_cause_analysis)

        if self.revision_suggestions:
            lines.append("")
            lines.append("--- Revision suggestions ---")
            for i, suggestion in enumerate(self.revision_suggestions, 1):
                lines.append(f"  {i}. {suggestion}")

        lines.append("=== END VERIFICATION REPORT ===")
        return "\n".join(lines)
