from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class SkillBundle:
    """A skill bundle (§3.1) — multi-file package of procedural guidance.

    Structure:
        name — skill identifier (e.g., "evo-period-detection")
        skillell — SKILL.md content (procedural workflow instructions)
        scripts — dict of {filename → content} for executable utility code
        metadata — parsed YAML frontmatter (name, description)
    """

    name: str
    metadata: dict = field(default_factory=dict)
    skillell: str = ""
    scripts: dict[str, str] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "metadata": self.metadata,
            "skillell": self.skillell,
            "scripts": self.scripts,
        }

    @classmethod
    def from_dict(cls, data: dict) -> SkillBundle:
        return cls(
            name=data["name"],
            metadata=data.get("metadata", {}),
            skillell=data.get("skillell", ""),
            scripts=data.get("scripts", {}),
        )


def parse_skill_dir(skill_dir: str | Path) -> SkillBundle:
    """Parse a skill directory on disk into a SkillBundle.

    Expected layout (SkillsBench or evolved format):
        skill_name/
            SKILL.md          (required)
            scripts/*.py      (optional)
            scripts/*.sh      (optional)

    The SKILL.md has YAML frontmatter with 'name' and 'description'.
    """
    skill_dir = Path(skill_dir)
    name = skill_dir.name

    skillell_path = skill_dir / "SKILL.md"
    skillell = ""
    metadata: dict = {}
    if skillell_path.exists():
        content = skillell_path.read_text()
        metadata, skillell = _parse_frontmatter(content)

    scripts: dict[str, str] = {}
    scripts_dir = skill_dir / "scripts"
    if scripts_dir.exists():
        for f in sorted(scripts_dir.rglob("*")):
            if f.is_file():
                rel_path = str(f.relative_to(scripts_dir))
                scripts[rel_path] = f.read_text()

    if "name" in metadata:
        name = metadata.pop("name")

    return SkillBundle(
        name=name,
        metadata=metadata,
        skillell=skillell,
        scripts=scripts,
    )


def parse_skill_from_text(content: str, default_name: str = "unnamed") -> SkillBundle:
    """Parse a SKILL.md text string into a SkillBundle.

    Used when a skill is generated by the LLM and returned as raw text.
    """
    metadata, skillell = _parse_frontmatter(content)
    name = metadata.pop("name", default_name)
    return SkillBundle(
        name=name,
        metadata=metadata,
        skillell=skillell,
    )


def _parse_frontmatter(text: str) -> tuple[dict, str]:
    """Parse YAML frontmatter from markdown text.

    Frontmatter is delimited by '---' lines at the start of the file.

    Returns (metadata_dict, remaining_text).
    """
    metadata: dict = {}
    if not text.startswith("---"):
        return metadata, text

    parts = text.split("---", 2)
    if len(parts) < 3:
        return metadata, text

    try:
        import yaml

        metadata = yaml.safe_load(parts[1]) or {}
    except Exception:
        pass

    remaining = parts[2].strip()
    return metadata, remaining


def serialize_skill(skill: SkillBundle) -> str:
    """Serialize a SkillBundle to a string (SKILL.md format)."""
    lines: list[str] = ["---"]
    if skill.metadata:
        for k, v in skill.metadata.items():
            lines.append(f"{k}: {v}")
    elif skill.name:
        lines.append(f"name: {skill.name}")
    lines.append("---")
    lines.append("")
    lines.append(skill.skillell)
    return "\n".join(lines)


def write_skill(skill: SkillBundle, target_dir: str | Path) -> Path:
    """Write a SkillBundle to disk in the standard layout.

    Creates:
        {target_dir}/{skill.name}/
            SKILL.md
            scripts/*.py
    """
    target_dir = Path(target_dir)
    skill_dir = target_dir / skill.name
    skill_dir.mkdir(parents=True, exist_ok=True)

    (skill_dir / "SKILL.md").write_text(serialize_skill(skill))

    if skill.scripts:
        scripts_dir = skill_dir / "scripts"
        scripts_dir.mkdir(exist_ok=True)
        for filename, content in skill.scripts.items():
            file_path = scripts_dir / filename
            file_path.parent.mkdir(parents=True, exist_ok=True)
            file_path.write_text(content)

    return skill_dir
